checkpoint-1タスク完了
HirokiMinagawa/tpa-04-cryptocurrency pull request #1
Opened 2019-01-14 17:17 UTC by HirokiMinagawa

レビューよろしくお願いします。

2019-01-15 04:00 UTC, obber requested changes
コメント残しときました！よろしくお願いしいます！

APIに関しては、最近APIがアップデートされてちょっと変わったみたいなので明日自分で叩いてみて確認して、もし注意点があったらまたコメントを残しときます！

みながわさんのapi-service.js のメモは見いい感じと思いました！

2019-01-15 04:00 UTC, obber commented on src/App.vue
> +      value: 'Metric Value',
ステップ１ではコンポーネント化するだけなので、データプロパティが一つしかないのは決して間違っていないのですが、６個の箱のために多分データオブジェクトのプロパティを六つ定義しないといけなくなりますよね！チャート以外のコンポーネントのために使うデータ型はわかっているので、この段階で定義しとくのはありだと思います。

それと、プロパティ名が `"value"` だけだと何を表すのかがわかりにくいので、６個の箱のためのプロパティ名を変えといてください！ 例えば、`"24HourChange"` など。

2019-01-15 04:00 UTC, obber commented on src/components/Metric.vue
> +  props: ['title', 'value'],
Nice job!

2019-01-17 09:45 UTC, jonatan-alama commented
LGTM!

2019-01-18 15:57 UTC, merged